name: Trigger cnspec bump in dependant repositories

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  trigger-cnspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [packer-plugin-cnspec]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Trigger cnspec bump in server
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.RELEASR_ACTION_TOKEN }}
          repository: "mondoohq/${{ matrix.repo }}"
          event-type: update-cnspec
          client-payload: '{
              "version": "${{  github.ref_name }}"
            }'
